"""schema inicial

Revision ID: 0bc0adf9ac13
Revises: 
Create Date: 2026-09-08 12:58:52.183923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bc0adf9ac13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # necessária para o índice trigram de busca de bairro (README "Painel de filtros")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emolumento_faixa',
    sa.Column('tabela', sa.String(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('limite_superior', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vigencia_inicio', sa.Date(), nullable=False),
    sa.Column('vigencia_fim', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imovel',
    sa.Column('uf', sa.CHAR(length=2), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('casa', 'apartamento', 'terreno', 'loja', 'outro', name='tipo_imovel', native_enum=False), nullable=False),
    sa.Column('area_total_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('area_privativa_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('area_terreno_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quartos', sa.Integer(), nullable=True),
    sa.Column('descricao_oficial', sa.String(), nullable=True),
    sa.Column('inscricao_municipal', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_imovel_bairro_trgm', 'imovel', ['bairro'], unique=False, postgresql_using='gin', postgresql_ops={'bairro': 'gin_trgm_ops'})
    op.create_index('ix_imovel_uf_cidade', 'imovel', ['uf', 'cidade'], unique=False)
    op.create_table('itbi_municipio',
    sa.Column('uf', sa.CHAR(length=2), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('aliquota_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fonte', sa.Enum('legislacao', 'agregador', name='fonte_itbi', native_enum=False), nullable=False),
    sa.Column('confianca', sa.Enum('confirmada', 'a_confirmar', 'desconhecida', name='confianca_itbi', native_enum=False), nullable=False),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uf', 'cidade', name='uq_itbi_municipio_uf_cidade')
    )
    op.create_table('usuario',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('importacao',
    sa.Column('fonte', sa.Enum('caixa', 'zukerman', name='fonte_leilao', native_enum=False), nullable=False),
    sa.Column('arquivo_nome', sa.String(), nullable=True),
    sa.Column('arquivo_hash', sa.String(), nullable=True),
    sa.Column('linhas_lidas', sa.Integer(), nullable=False),
    sa.Column('criados', sa.Integer(), nullable=False),
    sa.Column('atualizados', sa.Integer(), nullable=False),
    sa.Column('inalterados', sa.Integer(), nullable=False),
    sa.Column('erros', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('processando', 'concluida', 'falhou', name='status_importacao', native_enum=False), nullable=False),
    sa.Column('executada_por', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['executada_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_importacao_arquivo_hash'), 'importacao', ['arquivo_hash'], unique=False)
    op.create_table('parametro_usuario',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('prazo_carregamento_meses', sa.Integer(), nullable=False),
    sa.Column('comissao_corretor_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('piso_margem_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ir_aliquota_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('itbi_aliquota_padrao_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comissao_leiloeiro_padrao_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('lote_leilao',
    sa.Column('imovel_id', sa.Uuid(), nullable=False),
    sa.Column('fonte', sa.Enum('caixa', 'zukerman', name='fonte_leilao', native_enum=False), nullable=False),
    sa.Column('codigo_externo', sa.String(), nullable=False),
    sa.Column('modalidade', sa.String(), nullable=True),
    sa.Column('preco_venda', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_avaliacao', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('desconto_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('aceita_financiamento', sa.Boolean(), nullable=False),
    sa.Column('aceita_fgts', sa.Enum('nao_verificado', 'aceita', 'nao_aceita', name='aceita_fgts', native_enum=False), nullable=True),
    sa.Column('praca_1_valor', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('praca_1_data', sa.Date(), nullable=True),
    sa.Column('praca_2_valor', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('praca_2_data', sa.Date(), nullable=True),
    sa.Column('url_fonte', sa.String(), nullable=True),
    sa.Column('importacao_id', sa.Uuid(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['imovel_id'], ['imovel.id'], ),
    sa.ForeignKeyConstraint(['importacao_id'], ['importacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fonte', 'codigo_externo', name='uq_lote_fonte_codigo')
    )
    op.create_index('ix_lote_leilao_ativo', 'lote_leilao', ['ativo'], unique=False, postgresql_where=sa.text('ativo = true'))
    op.create_index(op.f('ix_lote_leilao_desconto_pct'), 'lote_leilao', ['desconto_pct'], unique=False)
    op.create_index(op.f('ix_lote_leilao_preco_venda'), 'lote_leilao', ['preco_venda'], unique=False)
    op.create_table('avaliacao',
    sa.Column('lote_id', sa.Uuid(), nullable=False),
    sa.Column('etapa', sa.Enum('nao_avaliado', 'pesquisa_campo', 'analise_financeira', 'decisao', 'aprovado_lance', 'descartado', name='etapa', native_enum=False), nullable=False),
    sa.Column('responsavel_id', sa.Uuid(), nullable=True),
    sa.Column('etapa_desde', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('motivo_descarte', sa.String(), nullable=True),
    sa.Column('teto_lance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('anotacoes', sa.String(), nullable=False),
    sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_leilao.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacao_etapa'), 'avaliacao', ['etapa'], unique=False)
    op.create_table('campo_avaliacao',
    sa.Column('avaliacao_id', sa.Uuid(), nullable=False),
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('valor_numerico', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valor_texto', sa.String(), nullable=True),
    sa.Column('origem', sa.Enum('base', 'manual', 'coleta_guiada', 'automacao', name='origem_campo', native_enum=False), nullable=False),
    sa.Column('fonte_declarada', sa.String(), nullable=True),
    sa.Column('preenchido_por', sa.Uuid(), nullable=True),
    sa.Column('preenchido_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sugestao_valor', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sugestao_origem', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacao.id'], ),
    sa.ForeignKeyConstraint(['preenchido_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avaliacao_id', 'chave', name='uq_campo_avaliacao_chave')
    )
    op.create_table('evento_avaliacao',
    sa.Column('avaliacao_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('importacao', 'campo_alterado', 'etapa_alterada', 'calculo', 'descarte', 'sugestao_aceita', name='tipo_evento', native_enum=False), nullable=False),
    sa.Column('ator_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ator_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evento_avaliacao')
    op.drop_table('campo_avaliacao')
    op.drop_index(op.f('ix_avaliacao_etapa'), table_name='avaliacao')
    op.drop_table('avaliacao')
    op.drop_index(op.f('ix_lote_leilao_preco_venda'), table_name='lote_leilao')
    op.drop_index(op.f('ix_lote_leilao_desconto_pct'), table_name='lote_leilao')
    op.drop_index('ix_lote_leilao_ativo', table_name='lote_leilao', postgresql_where=sa.text('ativo = true'))
    op.drop_table('lote_leilao')
    op.drop_table('parametro_usuario')
    op.drop_index(op.f('ix_importacao_arquivo_hash'), table_name='importacao')
    op.drop_table('importacao')
    op.drop_table('usuario')
    op.drop_table('itbi_municipio')
    op.drop_index('ix_imovel_uf_cidade', table_name='imovel')
    op.drop_index('ix_imovel_bairro_trgm', table_name='imovel', postgresql_using='gin', postgresql_ops={'bairro': 'gin_trgm_ops'})
    op.drop_table('imovel')
    op.drop_table('emolumento_faixa')
    # ### end Alembic commands ###
