"""margem desejada por imovel

Revision ID: 2401d8f8d029
Revises: 7c5b61dd1e8f
Create Date: 2026-09-14 22:53:38.721272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2401d8f8d029'
down_revision: Union[str, Sequence[str], None] = '7c5b61dd1e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avaliacao', sa.Column('margem_desejada_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avaliacao', 'margem_desejada_pct')
    # ### end Alembic commands ###
