"""evento_lote e campos de auditoria em importacao

Revision ID: 7c5b61dd1e8f
Revises: f7571fba38bf
Create Date: 2026-09-14 17:33:56.245668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c5b61dd1e8f'
down_revision: Union[str, Sequence[str], None] = 'f7571fba38bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento_lote',
    sa.Column('lote_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('importacao', 'campo_alterado', 'etapa_alterada', 'calculo', 'descarte', 'sugestao_aceita', name='tipo_evento', native_enum=False), nullable=False),
    sa.Column('importacao_id', sa.Uuid(), nullable=True),
    sa.Column('ator_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ator_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['importacao_id'], ['importacao.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_leilao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evento_lote_lote_id'), 'evento_lote', ['lote_id'], unique=False)
    op.add_column('importacao', sa.Column('arquivo_gerado_em', sa.Date(), nullable=True))
    op.add_column('importacao', sa.Column('inativados', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('importacao', sa.Column('reativados', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('importacao', 'reativados')
    op.drop_column('importacao', 'inativados')
    op.drop_column('importacao', 'arquivo_gerado_em')
    op.drop_index(op.f('ix_evento_lote_lote_id'), table_name='evento_lote')
    op.drop_table('evento_lote')
    # ### end Alembic commands ###
